// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-courses.ts
import { createClient } from "npm:@supabase/supabase-js@^2.101.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_courses_default = defineTool({
  name: "list_courses",
  title: "List courses",
  description: "List all courses owned by the signed-in user, including title, description, key, tempo, and time signature.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser(ctx).from("courses").select("id, title, description, key_root, key_quality, tempo, time_signature, updated_at").order("updated_at", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { courses: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-course.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.101.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_course_default = defineTool2({
  name: "get_course",
  title: "Get course with lessons",
  description: "Fetch a single course by id along with the ordered list of its lessons (course tabs).",
  inputSchema: {
    course_id: z.string().uuid().describe("The course id.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ course_id }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const sb = supabaseForUser2(ctx);
    const { data: course, error: e1 } = await sb.from("courses").select("id, title, description, key_root, key_quality, tempo, time_signature, updated_at").eq("id", course_id).maybeSingle();
    if (e1) return { content: [{ type: "text", text: e1.message }], isError: true };
    if (!course) return { content: [{ type: "text", text: "Course not found" }], isError: true };
    const { data: lessons, error: e2 } = await sb.from("course_tabs").select("id, title, position, key_root, key_quality, tempo, time_signature, updated_at").eq("course_id", course_id).order("position", { ascending: true });
    if (e2) return { content: [{ type: "text", text: e2.message }], isError: true };
    const payload = { course, lessons: lessons ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/create-course.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.101.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_course_default = defineTool3({
  name: "create_course",
  title: "Create course",
  description: "Create a new empty course for the signed-in user. Returns the new course id.",
  inputSchema: {
    title: z2.string().trim().min(1).max(200).describe("Course title."),
    description: z2.string().max(2e3).optional().describe("Optional description."),
    key_root: z2.string().max(4).optional().describe("Optional key root, e.g. 'G'."),
    key_quality: z2.string().max(32).optional().describe("Optional key quality, e.g. 'ionian'."),
    tempo: z2.number().int().min(20).max(400).optional().describe("Optional tempo BPM.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const row = { user_id: ctx.getUserId(), title: input.title };
    if (input.description !== void 0) row.description = input.description;
    if (input.key_root !== void 0) row.key_root = input.key_root;
    if (input.key_quality !== void 0) row.key_quality = input.key_quality;
    if (input.tempo !== void 0) row.tempo = input.tempo;
    const { data, error } = await supabaseForUser3(ctx).from("courses").insert(row).select("id, title").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Created course "${data.title}" (${data.id})` }],
      structuredContent: { course: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "cfpadpfgmuqxvoqmaztb";
var mcp_default = defineMcp({
  name: "fretboard-visions-mcp",
  title: "Fretboard Visions",
  version: "0.1.0",
  instructions: "Tools for the Fretboard Visions guitar app. Use `list_courses` to browse the signed-in user's courses, `get_course` to inspect a course and its lessons, and `create_course` to add a new one.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_courses_default, get_course_default, create_course_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
